version: '3'

services:
    nginx:
        container_name: ${DOCKER_PROJECT_NAME}-nginx
        image: nginx:stable-alpine
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./.docker/logs/nginx:/var/log/nginx/
        ports:
            - "${DOCKER_NGINX_PORT}:80"
        depends_on:
            - php7.4
            - postgres

    php7.4:
        container_name: ${DOCKER_PROJECT_NAME}-php7.4
        restart: unless-stopped
        working_dir: /var/www
        build:
            context: ./docker/php/7.4
        volumes:
            - ./:/var/www
            - ./docker/php/7.4/php.ini:/usr/local/etc/php/php.ini
        ports:
            - "${DOCKER_PHP_7_4_PORT}:9000"
        depends_on:
            - postgres

    postgres:
        container_name: ${DOCKER_PROJECT_NAME}-postgres-12
        image: postgres:12-alpine
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${DOCKER_POSTGRES_USER}
            POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}
        volumes:
            - ./docker/postgres/init:/docker-entrypoint-initdb.d
            - ./.docker/postgres/data:/var/lib/postgresql/data
        ports:
            - "${DOCKER_POSTGRES_PORT}:5432"

    #symfony/mailer
    # mailer:
    #   image: schickling/mailcatcher
    #   ports: [1025, 1080]
