version: '3'

services:
    postgres:
        container_name: ${DOCKER_PROJECT_NAME}-postgres-12
        image: postgres:12-alpine
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${DOCKER_POSTGRES_USER}
            POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}
        volumes:
          - ./docker/postgres/init:/docker-entrypoint-initdb.d
          - ./.docker/postgres/data:/var/lib/postgresql/data
        ports:
          - "${DOCKER_POSTGRES_PORT}:5432"

    #symfony/mailer
    # mailer:
    #   image: schickling/mailcatcher
    #   ports: [1025, 1080]
